version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: seo-agent-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dev-seo-agent
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: seo-agent-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: seo-agent-adminer
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata:
